### ISSUE TITLE
无法打开输入文件“opencv_world455.obj”

### ISSUE THREAD

**Issue by lhyciomp** [AIDajiangtang/Superpoint-LightGlue-Image-Stiching#12]
您好，感谢您的分享，但是在编译工程时，我遇到了一个错误 LINK : fatal error LNK1181: 无法打开输入文件“F:\code_workspace\Superpoint-LightGlue-Image-Stiching-main\opencv\lib\opencv_world455.obj” ,使用的是您提供的opencv库，编译器使用的是vs 2019 release msvc:"Visual Studio 16 2019",具体为：[cmake] -- The C compiler identification is MSVC 19.29.30154.0
[cmake] -- The CXX compiler identification is MSVC 19.29.30154.0。
请问这是什么问题呢，如何解决呢？

**Comment by AIDajiangtang** [comment]
1.确认编译release x64
2.确认F:\code_workspace\Superpoint-LightGlue-Image-Stiching-main\opencv\lib\这个目录下是否是有opencv_world455.lib

**Comment by lhyciomp** [comment]
好的，感谢解答，这两个条件应该都是没问题的。我使用的是visual studio code，后面换成visual studio就没什么问题，可能是我包含设置的问题。
