### ISSUE TITLE
SuperPoint的ONNX文件从何而来？

### ISSUE THREAD

**Issue by haithink** [AIDajiangtang/Superpoint-LightGlue-Image-Stiching#14]
请问SuperPoint的ONNX是怎么获取的呢？从某个现有模型文件转换而来的么？谢谢。

**Comment by haithink** [comment]
因为看模型调用结果，已经筛选出特征点了，应该是加了些后处理代码吧，模型本身只是给每个像素点计算出一个得分。

**Comment by AIDajiangtang** [comment]
> 型调用结果，已经筛选出特征点了，应该是加了些后处理代码吧，模型本身只是给每个像素点计算出一个得分。

链接: https://pan.baidu.com/s/1cMJW3LQZKeQWIJqWCzT2FA?pwd=uu9t 提取码: uu9t

**Comment by AIDajiangtang** [comment]
> 因为看模型调用结果，已经筛选出特征点了，应该是加了些后处理代码吧，模型本身只是给每个像素点计算出一个得分。

std::vector<int64_t> desshape = outputs[2].GetTensorTypeAndShapeInfo().GetShape();
	float* des = (float*)outputs[2].GetTensorMutableData<void>();

	Mat desmat = descriptors.getMat();
	desmat.create(Size(desshape[2], desshape[1]), CV_32FC1);
	for (int h = 0; h < desshape[1]; h++)
	{
		for (int w = 0; w < desshape[2]; w++)
		{
			int index = h * desshape[2] + w;
			desmat.at<float>(h, w) = des[index];
		}
	}
除了坐标，应该还有个置信度，可以看下desshape 维度信息

**Comment by haithink** [comment]
多谢回复！我是说ONNX是怎么转换来的。我用开源代码（基于tensorflow 1.5）训练出了SuperPoint模型，python版本推理正常。然后转出的ONNX模型推理的结果如果直接用得分来筛选会有特征点聚集的现象，还得额外再加NMS处理，这样操作以后特征点数量不太够用。但你的ONNX模型我测试发现不需要NMS，并且特征点也很多。

**Comment by AIDajiangtang** [comment]
> 转出的ONNX模型推理的结果如果直接用得分来筛选会有特征点聚集的现象，还

你看下你训练时图像归一化方法和我推理时的归一化方法一致吗？

**Comment by haithink** [comment]
> > 转出的ONNX模型推理的结果如果直接用得分来筛选会有特征点聚集的现象，还
> 
> 你看下你训练时图像归一化方法和我推理时的归一化方法一致吗？

哦，多谢，我检查下。。。

**Comment by haithink** [comment]
> > 转出的ONNX模型推理的结果如果直接用得分来筛选会有特征点聚集的现象，还
> 
> 你看下你训练时图像归一化方法和我推理时的归一化方法一致吗？

问题解决了，不是预处理的问题，是输出张量的选择问题。我用的https://github.com/rpautrat/SuperPoint 这个项目提供的模型转的ONNX，你的ONNX是自己训练的模型转出的么？感觉效果比你的略差一些呢。

**Comment by AIDajiangtang** [comment]
我是直接用别人训练好的模型

**Comment by haithink** [comment]
> 我是直接用别人训练好的模型

OK,多谢。
